language: java
sudo: required
install: true

jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: grrolland-github

script:
  - sh ./runSonarQubeAnalysis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false