language: java
sudo: required
install: true

jdk:
  - openjdk8
addons:
  sonarqube:
    organization: grrolland-github

script:
  - sh ./runSonarQubeAnalysis.sh

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
   provider: releases
   api_key: $GITHUB_OAUTH_TOKEN
   file:
     - target/ngx-distributed-shm-$project_version.jar
   skip_cleanup: true
   overwrite: true
   on:
     tags: true
     repo: grrolland/ngx-distributed-shm
     name: $project_version

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
