language: java
os: linux
dist: xenial

git:
  depth: false

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: grrolland-github

script:
  - mvn clean package
  - sh ./runSonarQubeAnalysis.sh

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
   - provider: releases
     token: $GITHUB_OAUTH_TOKEN
     file:
       - target/ngx-distributed-shm.jar
     overwrite: true
     on:
       tags: true
       repo: grrolland/ngx-distributed-shm
       name: $project_version
   - provider: script
     script: echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
     on:
       tags: false
   - provider: script
     script: echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
     on:
       tags: false
   - provider: script
     script: mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
     on:
       tags: false
   - provider: script
     script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
     on:
       tags: false

after_success:
  - bash .travis/pushimage.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
